os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - java -version
script:
  - mvn clean test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
